apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-min-config
  namespace: redis
data:
  redis.conf: |
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly no
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
    - port: 16379
      name: gossip
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  serviceName: redis-headless
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          command: ["redis-server", "/etc/redis/redis.conf"]
          resources:
            ## Base requests are strictly required for HPA to calculate usage percentages
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: conf
              mountPath: /etc/redis
      volumes:
        - name: conf
          configMap:
            name: redis-min-config