apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-entrypoint
  labels:
    app: entrypoint
spec:
  # Scaled to 6 to map perfectly to your 6-node physical topology. 
  # This ensures no single node handles all the ingress traffic.
  replicas: 6 
  selector:
    matchLabels:
      app: entrypoint
  template:
    metadata:
      labels:
        app: entrypoint
    spec:
      containers:
      - name: fastapi
        image: dockbudy360/fastapi-entrypoint:v2.2
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-cluster-service" 
        - name: REDIS_PORT
          value: "6379"
        # If your base image uses Uvicorn, this environment variable 
        # automatically tells it to spin up multiple worker processes.
        - name: WEB_CONCURRENCY
          value: "4" 
        resources:
          requests:
            cpu: "500m" # Request half a core
            memory: "256Mi"
          limits:
            # Increased to a full 2 cores. 
            # This gives Python the raw power it needs to route heavy traffic.
            cpu: "2" 
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-entrypoint-svc
spec:
  type: NodePort
  selector:
    app: entrypoint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080