USER-SUPPLIED VALUES:
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
# 1. Grafana Configuration
grafana:
  service:
    type: NodePort

# 2. Prometheus Configuration
prometheus:
  service:
    type: NodePort

  # Remote Write Receiver Configuration
  prometheusSpec:
    enableRemoteWriteReceiver: true
