apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redis-naive-hpa
spec:
  scaleTargetRef:
    apiVersion: databases.spotahome.com/v1
    kind: RedisFailover
    name: leaderboard-cache
  minReplicas: 3
  maxReplicas: 9
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70