apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-keda-scaler
spec:
  scaleTargetRef:
    apiVersion: databases.spotahome.com/v1
    kind: RedisFailover
    name: leaderboard-cache
  minReplicaCount: 3
  maxReplicaCount: 9
  cooldownPeriod: 300 # Wait 5 minutes before scaling back down to prevent thrashing
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-k8s.monitoring.svc.cluster.local:9090
      metricName: redis_connected_clients
      query: sum(redis_connected_clients{service="redis-cluster-service"})
      threshold: '500'