apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redis-hpa
  namespace: redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: ContainerResource # Changed from Resource
      containerResource:
        name: cpu
        container: redis # Targets only the main application
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
      scaleDown:
        # Forces the HPA to wait 5 minutes after CPU drops before terminating a pod
        stabilizationWindowSeconds: 300 
        policies:
        - type: Pods
          value: 1
          periodSeconds: 60 # Only kill 1 pod per minute maximum