apiVersion: v1
kind: Service
metadata:
  name: fastapi-leaderboard-svc
  namespace: fastapi-leaderboard
spec:
  type: NodePort
  selector:
    # This must perfectly match the label in your deployment template
    app: fastapi-leaderboard 
  ports:
    - port: 8000
      targetPort: 8000